# Generated by Django 5.0.3 on 2024-03-21 05:54

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateField(auto_now=True)),
                ('materia', models.CharField(max_length=264)),
                ('actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateField(auto_now=True)),
                ('titulo', models.CharField(max_length=264)),
                ('subtitulo', models.CharField(blank=True, max_length=264, null=True)),
                ('autor', models.CharField(max_length=264)),
                ('body', ckeditor.fields.RichTextField()),
                ('actualizacion', models.DateTimeField(auto_now_add=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.materia')),
            ],
        ),
    ]
