# Generated by Django 5.0.3 on 2024-03-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateField(auto_now=True)),
                ('actualizacion', models.DateField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=264)),
                ('creador', models.CharField(max_length=264)),
                ('tiktok', models.CharField(blank=True, max_length=264, null=True)),
                ('facebook', models.CharField(blank=True, max_length=264, null=True)),
                ('correo', models.CharField(blank=True, max_length=264, null=True)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
